languageCode = "en-us"
title = "Blog | Federico Marani"
theme = "crisp"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
relativeurls = true

[params]
DateFormat = "2 Jan 2006"
description = "Senior Engineer/Architect, open-source enthusiast, Linux addict. Former Head of Engineering @TrialReach, CTO at TalentRank. "
author = "Federico Marani"
